---
title: Schools and Programmes of Public Health
subtitle: A Review
author:
  - name: Proochista Ariana
    orcid: 0000-0002-0154-2237
    email: proochista.ariana@ndm.ox.ac.uk
    affiliation:
      - name: Centre for Tropical Medicine and Global Health, Nuffield Department of Medicine, University of Oxford
        city: Oxford
date: "`r format(Sys.Date(), '%d %B %Y')`"
format: 
  html:
    toc: true
    toc-location: left
    embed-resources: true
    grid:
      body-width: 900px
      margin-width: 300px
    code-tools:
      source: https://github.com/OxfordIHTM/spph-review/blob/main/reports/spph_review.qmd
---

```{r setup}
#| echo: false

suppressPackageStartupMessages(source(here::here("packages.R")))
for (f in list.files(here::here("R"), full.names = TRUE)) source (f)

targets::tar_load(
  c(
    sr_public_health_rankings, the_overall_rankings, qs_overall_rankings,
    ph_master_programme_list, ph_review_data_released, module_categories,
    module_options_categories, table_core_module_categories, table_option_module_categories, table_institutions_countries, table_institutions_regions, barplot_institution_countries, barplot_institution_regions, barplot_core_module_categories, barplot_option_module_categories
  )
)
```


## Methods

## Results

### Summary

```{r}
#| label: tbl-rankings-table
#| tbl-cap: Top 30 Public Health Schools and Programmes
#| html-table-processing: none
#| echo: false

ph_review_data_released |>
  dplyr::select(rank, institution) |>
  knitr::kable() |>
  kableExtra::kable_styling(
    bootstrap_options = c("striped", "bordered"),
    position = "center",
    full_width = FALSE
  )
```


#### Institutions by country

```{r}
#| label: fig-institutions-by-country
#| fig-cap: Top 30 Public Health Schools and Programmes by Country
#| fig-width: 10
#| fig-height: 12
#| message: false
#| warning: false
#| echo: false

barplot_institution_countries
```

#### Institutions by region

```{r}
#| label: fig-institutions-by-region
#| fig-cap: Top 30 Public Health Schools and Programmes by Region
#| fig-width: 10
#| fig-height: 12
#| message: false
#| warning: false
#| echo: false

barplot_institution_regions
```

### Core modules

```{r}
#| label: fig-core-modules
#| fig-cap: Core modules themes
#| fig-width: 14
#| fig-height: 12
#| message: false
#| warning: false
#| echo: false

barplot_core_module_categories
```


```{r}
#| label: fig-modules-options
#| fig-cap: Module options themes
#| fig-width: 14
#| fig-height: 12
#| message: false
#| warning: false
#| echo: false

barplot_option_module_categories
```
