name: run workflow

on:
  workflow_dispatch:

jobs:
  run-workflow:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      # - name: Install system dependencies
      #   run: |
      #     apt-get update && apt-get install -y --no-install-recommends \
      #     libxt6 libglpk-dev libpoppler-cpp-dev
          
      # - name: Trust git repo
      #   run: |
      #     git config --global --add safe.directory /__w/spph-review/spph-review
          
      - name: Install packages from renv.lock (with cache)
        if: ${{ !env.ACT }}  
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2

      - name: Install packages from renv.lock (local, no cache)
        if: ${{ env.ACT }}
        run: |
          renv::restore()
        shell: Rscript {0}
        
      - name: Run workflow
        run: |
          targets::tar_make(qs_overall_rankings)
          targets::tar_make(the_overall_rankings)
          targets::tar_make(sr_overall_rankings)
          targets::tar_make(aspph_members_list)
          targets::tar_make(aspher_members_list)
        shell: Rscript {0}